from dataclasses import dataclass
from typing import List, Optional, Protocol, runtime_checkable


@dataclass(frozen=True)
class LlmSummary:
    """LLM-generated summary of an incident."""
    text: str


@dataclass(frozen=True)
class MitigationSuggestion:
    """Mitigation suggestion generated by LLM."""
    confidence: Optional[str] = None
    investigation: Optional[str] = None
    mitigation: Optional[str] = None
    resolution_note: Optional[str] = None
    related_incidents: List[str] = None

    def __post_init__(self):
        if self.related_incidents is None:
            object.__setattr__(self, "related_incidents", [])


@dataclass(frozen=True)
class LlmUsage:
    """Usage and cost telemetry returned by the LLM gateway."""
    model: Optional[str] = None
    tokens_in: Optional[int] = None
    tokens_out: Optional[int] = None
    tokens_total: Optional[int] = None
    estimated_cost: Optional[float] = None


@dataclass(frozen=True)
class IncidentEnrichment:
    """Result from LLM enrichment of an incident."""
    summary: Optional[LlmSummary] = None
    mitigation_suggestions: List[MitigationSuggestion] = None
    related_incidents: List[str] = None
    usage: Optional[LlmUsage] = None

    def __post_init__(self):
        # Ensure mitigation_suggestions is a list
        if self.mitigation_suggestions is None:
            object.__setattr__(self, "mitigation_suggestions", [])
        if self.related_incidents is None:
            object.__setattr__(self, "related_incidents", [])


class LlmGatewayError(RuntimeError):
    """Raised when LLM gateway cannot serve a request."""


class LlmGatewayUnavailableError(LlmGatewayError):
    """Raised when the LLM gateway is temporarily unavailable."""


class LlmGatewayConfigurationError(LlmGatewayError):
    """Raised when LLM gateway is misconfigured."""


class LlmGatewayDisabledError(LlmGatewayError):
    """Raised when LLM gateway is disabled."""


@runtime_checkable
class LlmGateway(Protocol):
    """Protocol for LLM gateway integration.
    
    Implementations must provide LLM capabilities for enriching incident data.
    """
    
    def enrich_incident(
        self,
        incident_id: str,
        short_description: Optional[str],
        description: Optional[str],
        max_tokens: Optional[int] = None,
        main_incident_context: Optional[str] = None,
        related_incident_context: Optional[str] = None,
        same_title_incident_context: Optional[str] = None,
        use_fallback_prompt: bool = False,
    ) -> IncidentEnrichment:
        """Enrich an incident with LLM-generated content.

        Args:
            incident_id: Unique identifier for the incident
            short_description: Brief incident summary
            description: Detailed incident description
            max_tokens: Maximum tokens for LLM response (uses default if None)
            main_incident_context: Full sanitized main-incident context
            related_incident_context: Explicitly referenced related incident evidence
            same_title_incident_context: Matching same-title historical incident evidence

        Returns:
            IncidentEnrichment with summary and suggestions

        Raises:
            LlmGatewayUnavailableError: If the gateway is temporarily unavailable
            LlmGatewayConfigurationError: If the gateway is misconfigured
            LlmGatewayDisabledError: If the gateway is disabled
        """
